version: '3'

services:
  web:
    build: .
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
  mariadb:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: bdd
      MYSQL_ROOT_PASSWORD: "Password0"
      MYSQL_USER: "dalkia"
      MYSQL_PASSWORD: "esigelec"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8000:80
    depends_on:
      - web
      - mariadb
  debian:
    build: ./python
    depends_on:
      - mariadb
    command: tail -f /dev/null
    volumes:
      - ./python:/usr/src/
    

